<a href="https://colab.research.google.com/github/Tankasala25/PyTorch/blob/main/CreatingTensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Creating Tensors in PyTorch

In PyTorch, tensors are the main way we store and work with data.  
They are similar to NumPy arrays but with extra power for GPUs and deep learning.

---

## 1. Import Libraries
We start by importing **PyTorch** (`torch`) and Python's built-in **math** library.


In [ ]:
import torch
import math


---

## 2. Creating an Empty Tensor

The simplest way to create a tensor is using `torch.empty()`.  
This creates a tensor of the given size, but it does **not** initialize the values.  
So the numbers inside will look random (whatever was in memory before).


In [ ]:
# Create a 2D tensor with 3 rows and 4 columns
x = torch.empty(3, 4)

print("Type of x:", type(x))
print("Tensor x:\n", x)


Type of x: <class 'torch.Tensor'>
Tensor x:
 tensor([[1.1181e-13, 0.0000e+00, 0.0000e+00, 1.5046e-36],
        [1.0277e-13, 0.0000e+00, 1.0842e-19, 0.0000e+00],
        [2.8567e-10, 0.0000e+00, 2.8577e-10, 0.0000e+00]])


---

## 3. Understanding Dimensions

- A **1D tensor** is like a vector: `[1, 2, 3]`  
- A **2D tensor** is like a matrix: a table with rows and columns  
- Tensors with **3 or more dimensions** are just called "tensors"  

Let's create a few examples:


In [ ]:
# 1D tensor (vector with 5 elements)
v = torch.empty(5)
print("1D Tensor (vector):\n", v)

# 2D tensor (matrix with 2 rows, 3 columns)
m = torch.empty(2, 3)
print("\n2D Tensor (matrix):\n", m)

# 3D tensor (for example, 2 matrices stacked)
t = torch.empty(2, 3, 4)  # shape: (2 blocks, each 3x4 matrix)
print("\n3D Tensor:\n", t)


1D Tensor (vector):
 tensor([2.8607e-10, 0.0000e+00, 2.8568e-10, 0.0000e+00, 1.1210e-43])

2D Tensor (matrix):
 tensor([[2.7954e-10, 0.0000e+00, 0.0000e+00],
        [1.4013e-45, 0.0000e+00, 0.0000e+00]])

3D Tensor:
 tensor([[[2.8225e-10, 0.0000e+00, 2.8718e-10, 0.0000e+00],
         [8.9683e-44, 0.0000e+00, 1.1210e-43, 0.0000e+00],
         [1.4493e-10, 0.0000e+00, 1.1066e-13, 0.0000e+00]],

        [[1.3452e-43, 0.0000e+00, 4.4842e-44, 0.0000e+00],
         [2.9102e-10, 0.0000e+00, 0.0000e+00, 1.4013e-45],
         [1.7937e-43, 0.0000e+00, 1.5695e-43, 0.0000e+00]]])


---

## 4. Important Note

Since `torch.empty()` does not set values, what you see inside are **random garbage values from memory**.  


# Initialized Tensors in PyTorch  
When you work with neural networks or data, you often need **starting values**.  
PyTorch provides factory methods to quickly create tensors without manually typing numbers.

---


## 1. `torch.zeros(shape)`  
Creates a tensor filled with **all zeros**.  
Useful when you want an “empty slate” to begin with.


In [ ]:
import torch

t1 = torch.zeros((2,3))
print(t1)


tensor([[0., 0., 0.],
        [0., 0., 0.]])


## 2. `torch.ones(shape)`  
Creates a tensor filled with **all ones**.  
Handy when you want uniform starting values.


In [ ]:
t2 = torch.ones((2,2))
print(t2)


tensor([[1., 1.],
        [1., 1.]])


## 3. `torch.full(shape, fill_value)`  
Creates a tensor where every element is the same number you give.  
Example: a 3×3 tensor filled with `7`.


In [ ]:
t3 = torch.full((3,3), 7)
print(t3)


tensor([[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]])


## 4. `torch.rand(shape)`  
Creates a tensor filled with **random numbers** between `0` (inclusive) and `1` (exclusive).  
Good for initializing weights randomly.


In [ ]:
t4 = torch.rand((2,4))
print(t4)


tensor([[0.1734, 0.7609, 0.8734, 0.2438],
        [0.8840, 0.3708, 0.5074, 0.1900]])


## When to use which?
- **Zeros** → starting point, placeholder, or padding.  
- **Ones** → when you want everything equal, or for testing.  
- **Full** → when a constant value is needed.  
- **Rand** → when you need randomness to break symmetry (common in training neural nets).  

👉 In short:  
These methods let you quickly create tensors **without writing values yourself**.


# Random Tensor Families — Ranges & Distributions  

PyTorch provides different functions to create **random tensors**.  
Each one follows a specific **distribution** or **range of values**.

---


## 1. `torch.rand(shape)`  
- Values come from a **uniform distribution** in **[0, 1)**.  
- Always **non-negative**, never reaches 1.

In [ ]:
import torch

print("rand [0,1):\n", torch.rand(2, 3))


rand [0,1):
 tensor([[0.6398, 0.8276, 0.7593],
        [0.2127, 0.7273, 0.7996]])


## 2. `torch.randn(shape)`  
- Values come from a **normal (Gaussian)** distribution.  
- Mean = 0, Standard Deviation = 1.  
- Can be **negative**, **positive**, and even beyond 1.


In [ ]:
print("randn (normal 0±1):\n", torch.randn(2, 3))


randn (normal 0±1):
 tensor([[ 1.2268, -0.6588, -0.0622],
        [ 0.7005,  1.1285, -0.5114]])


## 3. `torch.randint(low, high, shape)`  
- Generates **integers** in the range `[low, high)`.  
- Negative numbers are possible if `low < 0`.  
- The upper bound `high` is **exclusive**.


In [ ]:
print("randint 0..9:\n", torch.randint(0, 10, (2, 3)))   # values 0–9
print("\nrandint -5..4:\n", torch.randint(-5, 5, (2, 3)))  # values -5–4


randint 0..9:
 tensor([[4, 8, 7],
        [1, 9, 6]])

randint -5..4:
 tensor([[ 3,  3, -2],
        [-3,  4, -5]])


## ✅ Answers to Common Doubts  
- `rand()` → always in **[0,1)** (positive only).  
- `randn()` → values centered around **0** (can be negative or greater than 1).  
- `randint(a, b, …)` → integers in `[a, b)`. You can choose **negative or positive ranges**.  


# Reproducibility with `torch.manual_seed`

Random numbers in PyTorch are generated by a *Random Number Generator (RNG)*.  
By setting a **seed value**, we can make the RNG give the **same sequence of random numbers every run**.

---


## Key Points
- **Same seed** ⇒ **same sequence** of random numbers (reproducible).  
- **Different seed** ⇒ different sequence.  
- You can reseed any time to restart the sequence from the beginning.  
- For GPU tensors, you can also set:  
  `torch.cuda.manual_seed_all(seed)`  


In [ ]:
import torch

# Same seed → same results
torch.manual_seed(42)
r1 = torch.rand(2, 3)

torch.manual_seed(42)
r2 = torch.rand(2, 3)

# Different seed → different results
torch.manual_seed(7)
r3 = torch.rand(2, 3)

# Any integer works (1729 is just an example)
torch.manual_seed(1729)
r4 = torch.rand(2, 3)

print("Seed 42 - first:\n", r1)
print("\nSeed 42 - second (identical):\n", r2)
print("\nSeed 7:\n", r3)
print("\nSeed 1729:\n", r4)


Seed 42 - first:
 tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

Seed 42 - second (identical):
 tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

Seed 7:
 tensor([[0.5349, 0.1988, 0.6592],
        [0.6569, 0.2328, 0.4251]])

Seed 1729:
 tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])


## ✅ Summary
- Setting a seed "locks in" the random sequence.  
- Useful for **debugging and reproducibility** (others can run your code and get the same results).  
- Seed values can be **any integer** .  
