<a href="https://colab.research.google.com/github/Tankasala25/PyTorch/blob/main/Practice3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🧠 PyTorch Dtypes — Simple Practicals

This notebook covers:

- Different dtypes  
- Creating tensors (by data & by shape)  
- Checking shape, dtype, device  
- Moving CPU ↔ GPU  
- NumPy ↔ Tensor conversions  
- Implicit & explicit casting  
- Precision order  
- Upcasting & downcasting


In [1]:
import torch
import numpy as np

print("PyTorch version:", torch.__version__)


PyTorch version: 2.8.0+cu126


## 1️⃣ Common PyTorch Data Types


In [2]:
dtypes = [
    torch.bool,
    torch.uint8,
    torch.int8, torch.int16, torch.int32, torch.int64,
    torch.float16, torch.float32, torch.float64,
    torch.complex64, torch.complex128
]

for dt in dtypes:
    t = torch.zeros((2,2), dtype=dt)
    print(dt, "-> bytes per element:", t.element_size())


torch.bool -> bytes per element: 1
torch.uint8 -> bytes per element: 1
torch.int8 -> bytes per element: 1
torch.int16 -> bytes per element: 2
torch.int32 -> bytes per element: 4
torch.int64 -> bytes per element: 8
torch.float16 -> bytes per element: 2
torch.float32 -> bytes per element: 4
torch.float64 -> bytes per element: 8
torch.complex64 -> bytes per element: 8
torch.complex128 -> bytes per element: 16


## 2️⃣ Creating Tensors (by shape and dtype)


In [3]:
t1 = torch.zeros((2,3), dtype=torch.int32)
t2 = torch.ones((2,3), dtype=torch.float32)
t3 = torch.rand((2,3), dtype=torch.float64)

print(t1)
print(t2)
print(t3)


tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.0118, 0.2321, 0.2416],
        [0.8707, 0.6660, 0.4734]], dtype=torch.float64)


## 3️⃣ torch.tensor(data) vs Factory Functions


In [4]:
# From data (shape comes from data)
t_values = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(t_values)
print("Shape:", t_values.shape)

# If you give numbers directly, it's not a shape
t_wrong = torch.tensor((2, 3))
print(t_wrong)
print("Shape:", t_wrong.shape)


tensor([[1, 2, 3],
        [4, 5, 6]])
Shape: torch.Size([2, 3])
tensor([2, 3])
Shape: torch.Size([2])


## 4️⃣ Tensor Attributes


In [5]:
t = torch.rand((2,3))
print(t)
print("Shape:", t.shape)
print("Dtype:", t.dtype)
print("Device:", t.device)

tensor([[0.3958, 0.6968, 0.1328],
        [0.8732, 0.2779, 0.8533]])
Shape: torch.Size([2, 3])
Dtype: torch.float32
Device: cpu


## 5️⃣ Moving Between CPU and GPU


In [6]:
t = torch.rand((2,3))
print("Before:", t.device)

if torch.cuda.is_available():
    t_gpu = t.to("cuda")
    print("Moved to GPU:", t_gpu.device)
    t_cpu = t_gpu.to("cpu")
    print("Moved back to CPU:", t_cpu.device)
else:
    print("No GPU found, tensor stays on CPU.")


Before: cpu
No GPU found, tensor stays on CPU.


## 6️⃣ NumPy ↔ Tensor Conversions


In [7]:
# NumPy to Tensor (shared memory)
arr = np.array([1, 2, 3], dtype=np.float32)
t_shared = torch.from_numpy(arr)
print("NumPy:", arr)
print("Tensor (shared):", t_shared)

# Changing NumPy affects tensor
arr[0] = 99
print("After changing NumPy:")
print("NumPy:", arr)
print("Tensor:", t_shared)

# Safe independent copy
t_copy = torch.tensor(arr)
arr[1] = 555
print("After changing again:")
print("NumPy:", arr)
print("Tensor copy (no change):", t_copy)

# Tensor to NumPy
t = torch.tensor([10., 20., 30.])
arr2 = t.numpy()
print("Tensor:", t)
print("NumPy:", arr2)

t[0] = 100
print("After changing tensor:")
print("Tensor:", t)
print("NumPy:", arr2)


NumPy: [1. 2. 3.]
Tensor (shared): tensor([1., 2., 3.])
After changing NumPy:
NumPy: [99.  2.  3.]
Tensor: tensor([99.,  2.,  3.])
After changing again:
NumPy: [ 99. 555.   3.]
Tensor copy (no change): tensor([99.,  2.,  3.])
Tensor: tensor([10., 20., 30.])
NumPy: [10. 20. 30.]
After changing tensor:
Tensor: tensor([100.,  20.,  30.])
NumPy: [100.  20.  30.]


## 7️⃣ Casting: Implicit and Explicit


In [8]:
# Implicit (PyTorch decides)
a = torch.tensor([1, 2, 3], dtype=torch.int32)
b = torch.tensor([1.5, 2.5, 3.5], dtype=torch.float32)
c = a + b
print("a dtype:", a.dtype)
print("b dtype:", b.dtype)
print("Result dtype:", c.dtype)

# Explicit (we choose)
x = torch.tensor([1.7, 2.9, 3.1])
print("Original tensor:", x)
print("To int:", x.int())
print("To float64:", x.double())
print("To float16:", x.half())


a dtype: torch.int32
b dtype: torch.float32
Result dtype: torch.float32
Original tensor: tensor([1.7000, 2.9000, 3.1000])
To int: tensor([1, 2, 3], dtype=torch.int32)
To float64: tensor([1.7000, 2.9000, 3.1000], dtype=torch.float64)
To float16: tensor([1.7002, 2.9004, 3.0996], dtype=torch.float16)


## 8️⃣ Precision Order (Type Promotion)


In [9]:
# int + float = float
a = torch.tensor([1], dtype=torch.int16)
b = torch.tensor([2.5], dtype=torch.float32)
print("int + float →", (a+b).dtype)

# float + complex = complex
f = torch.tensor([1.0], dtype=torch.float32)
z = torch.tensor([2+3j], dtype=torch.complex64)
print("float + complex →", (f+z).dtype)


int + float → torch.float32
float + complex → torch.complex64


## 9️⃣ Upcasting vs Downcasting


In [10]:
# Upcasting (safe)
t1 = torch.tensor([1.2345], dtype=torch.float32)
t2 = t1.to(torch.float64)
print("Upcast:", t1, "->", t2)

# Downcasting (precision lost)
x = torch.tensor([1.23456789], dtype=torch.float64)
y = x.to(torch.float32)
print("Downcast:", x, "->", y)

# Integer overflow
big = torch.tensor([100000], dtype=torch.int32)
small = big.to(torch.int16)
print("Int overflow:", big, "->", small)


Upcast: tensor([1.2345]) -> tensor([1.2345], dtype=torch.float64)
Downcast: tensor([1.2346], dtype=torch.float64) -> tensor([1.2346])
Int overflow: tensor([100000], dtype=torch.int32) -> tensor([-31072], dtype=torch.int16)


## ✅ Summary

| Concept | Description |
|----------|-------------|
| `torch.from_numpy()` | Shares memory with NumPy |
| `tensor.numpy()` | Shares memory with Tensor |
| `torch.tensor()` | Makes a new copy |
| `.to("cpu")`, `.cpu()` | Move to CPU |
| `.to("cuda")`, `.cuda()` | Move to GPU |
| Implicit casting | Automatic dtype conversion |
| Explicit casting | Manual using `.to()`, `.int()`, `.float()` |
| Upcasting | Safe (no data loss) |
| Downcasting | Can lose precision |
