<a href="https://colab.research.google.com/github/Tankasala25/PyTorch/blob/main/Practice2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

torch.__version__

'2.8.0+cu126'

In [ ]:
scalar=torch.tensor(5)
scalar.ndim,scalar.shape

(0, torch.Size([]))

In [ ]:
vector=torch.tensor([2,3])
vector.ndim,vector.shape

(1, torch.Size([2]))

In [ ]:
matrix=torch.tensor([[2,3],[4,5]])
matrix.ndim,matrix.shape

(2, torch.Size([2, 2]))

In [ ]:
tensor=torch.tensor([[[2,3],[4,5],[6,7]]])
tensor.ndim,tensor.shape

(3, torch.Size([1, 3, 2]))

In [ ]:
x=torch.rand([1,3,2])
x

tensor([[[0.8811, 0.2712],
         [0.9626, 0.1077],
         [0.3776, 0.3369]]])

In [ ]:
x_random=torch.rand([3,3,4])
x_random,

(tensor([[[0.4078, 0.2983, 0.5094, 0.1083],
          [0.9374, 0.4827, 0.0927, 0.6211],
          [0.7040, 0.1973, 0.8000, 0.4817]],
 
         [[0.8458, 0.9582, 0.8561, 0.0107],
          [0.8423, 0.8174, 0.8239, 0.3292],
          [0.1234, 0.3968, 0.5185, 0.7276]],
 
         [[0.6126, 0.1032, 0.3421, 0.8294],
          [0.6866, 0.0273, 0.0054, 0.4072],
          [0.3063, 0.6760, 0.0326, 0.7379]]]),)

In [ ]:
x=torch.rand([3,2])
x

tensor([[0.8270, 0.8707],
        [0.4186, 0.1534],
        [0.5443, 0.2247]])

In [ ]:
x=torch.zeros([3,2])
x

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [ ]:
y=torch.ones([3,2])
y

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [ ]:
x_like =torch.zeros_like(x_random)
x_like

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
ones=torch.ones(2,2,dtype=torch.int32)
print(ones)
print(ones.dtype)


tensor([[1, 1],
        [1, 1]], dtype=torch.int32)
torch.int32


In [ ]:
h=torch.tensor([1.2,2.3],dtype=torch.float16)
print(h)
print(h.dtype)

tensor([1.2002, 2.3008], dtype=torch.float16)
torch.float16


In [ ]:
i= torch.tensor([1,2,3],dtype=torch.int32)
print(i)
print(i.dtype)
print(i.shape)

tensor([1, 2, 3], dtype=torch.int32)
torch.int32
torch.Size([3])


In [ ]:
z=torch.empty((2,3),dtype=torch.float64)
print(z)
print(z.dtype)

tensor([[6.6477e-310, 6.6480e-310, 5.7571e-317],
        [6.6480e-310, 6.6480e-310, 6.6480e-310]], dtype=torch.float64)
torch.float64


In [ ]:
t=torch.rand(2,3)
print(t.device)
if torch.cuda.is_available():
  t_gpu=t.to("cuda")
  print(t_gpu.device)

cpu


In [ ]:
import torch
import numpy as np


arr= np.array([1,2,3],dtype=np.float32)
print(arr)
print(arr.dtype)

t1=torch.tensor(arr)
print(t1,t1.shape,t1.dtype)

arr[0]=7.0
print(arr)
print(t1)

[1. 2. 3.]
float32
tensor([1., 2., 3.]) torch.Size([3]) torch.float32
[7. 2. 3.]
tensor([1., 2., 3.])


In [ ]:
t2=torch.tensor([[4.,5.,6.],
                 [7.,8.,9.]],dtype=torch.float32)
print(t2)
print(t2.dtype)

arr2=t2.numpy()
print(arr2)
print(arr2.dtype)

t2[0,1]=23.0
print(t2)
print(arr2)



tensor([[4., 5., 6.],
        [7., 8., 9.]])
torch.float32
[[4. 5. 6.]
 [7. 8. 9.]]
float32
tensor([[ 4., 23.,  6.],
        [ 7.,  8.,  9.]])
[[ 4. 23.  6.]
 [ 7.  8.  9.]]
