<a href="https://colab.research.google.com/github/Tankasala25/PyTorch/blob/main/Practice1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Create a 4×5 empty tensor and print its type and shape.

In [2]:
import torch

x=torch.empty(4,5)
print("type :" ,type(x))
print("shape :" ,x.shape)

type : <class 'torch.Tensor'>
shape : torch.Size([4, 5])


Create the following tensors and print them:

A 2×2 tensor of zeros

A 2×2 tensor of ones

A 3×3 tensor filled with the number 9

👉 After creating them, also print their shape.

In [5]:
x=torch.zeros(2,2)
y=torch.ones(2,2)
z=torch.full((3,3),9)

print(x)
print(x.shape)
print(y)
print(y.shape)
print(z)
print(z.shape)

tensor([[0., 0.],
        [0., 0.]])
torch.Size([2, 2])
tensor([[1., 1.],
        [1., 1.]])
torch.Size([2, 2])
tensor([[9, 9, 9],
        [9, 9, 9],
        [9, 9, 9]])
torch.Size([3, 3])


Create a 1D tensor with 7 elements.

In [10]:
x=torch.empty(7)
print(x)
print(x.shape)

tensor([1.9452e-22, 0.0000e+00, 0.0000e+00, 0.0000e+00, 1.6255e-43, 0.0000e+00,
        1.1351e-43])
torch.Size([7])


Create a 2D tensor with shape (3, 4).

In [11]:
x=torch.empty(3,4)
print(x)
print(x.shape)

tensor([[1.7772e-22, 0.0000e+00, 1.3088e-22, 0.0000e+00],
        [1.1210e-43, 0.0000e+00, 8.9683e-44, 0.0000e+00],
        [1.5692e-40, 0.0000e+00, 0.0000e+00, 1.5046e-36]])
torch.Size([3, 4])


Create a 3D tensor with shape (2, 3, 4).

In [9]:
x=torch.empty(2,3,4)
print(x)
print(x.shape)

tensor([[[-8.1126e-33,  4.4714e-41, -8.1126e-33,  4.4714e-41],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  7.7052e+31,  1.9447e+31]],

        [[ 2.1715e-18,  2.3081e-12,  1.8590e+34,  7.7767e+31],
         [ 1.7181e+19,  1.8990e+28,  1.5766e-19,  2.1707e-18],
         [ 4.5447e+30,  3.0750e+29,  1.9284e+31,  1.8891e+31]]])
torch.Size([2, 3, 4])


Create a 2×3 tensor using torch.rand → check if values are between 0 and 1.

In [12]:
x=torch.rand(2,3)
print(x)

tensor([[0.2474, 0.4375, 0.6751],
        [0.8107, 0.3498, 0.7963]])


Create a 2×3 tensor using torch.randn → check if you get negative values as well.

In [17]:
x=torch.randn(2,3)
print(x)

tensor([[ 0.1649, -1.0475,  0.0792],
        [ 1.6739,  1.3626, -0.1148]])


Create a 2×4 tensor using torch.randint(5, 15, (2, 4)) → confirm values are between 5 and 14.

In [14]:
x=torch.randint(5,15,(2,4))
print(x)

tensor([[ 6, 12,  6,  6],
        [ 7, 11,  8, 11]])


Create a 2×5 tensor using torch.randint(-3, 3, (2, 5)) → confirm values are between -3 and 2.

Also count how many of them are negative.

In [15]:
x=torch.randint(-3,3,(2,5))
print(x)

tensor([[ 2,  0,  2, -1, -3],
        [ 2, -1, -2, -3, -2]])


Set seed = 99 and generate a 2×3 tensor with torch.rand.

In [18]:
torch.manual_seed(99)
x=torch.rand(2,3)
print(x)


tensor([[0.1033, 0.9702, 0.9481],
        [0.9787, 0.3268, 0.9200]])


Reset seed = 99 and generate again → confirm they are identical.

In [19]:
torch.manual_seed(99)
y=torch.rand(2,3)
print(y)


tensor([[0.1033, 0.9702, 0.9481],
        [0.9787, 0.3268, 0.9200]])


Set seed = 123 and compare with seed = 99 result → confirm they are different.

In [20]:
torch.manual_seed(123)
x=torch.rand(2,3)
print(x)

tensor([[0.2961, 0.5166, 0.2517],
        [0.6886, 0.0740, 0.8665]])


Try generating without resetting seed → see if results change.

In [21]:
x=torch.rand(2,3)
print(x)

tensor([[0.1366, 0.1025, 0.1841],
        [0.7264, 0.3153, 0.6871]])


In [22]:
import torch

# Create many random values
torch.manual_seed(42)       # reproducibility
x = torch.randn(10000)      # 10,000 samples

print("Sample mean:", x.mean().item())
print("Sample std :", x.std().item())
print("Minimum value:", x.min().item())
print("Maximum value:", x.max().item())


Sample mean: 0.00643951864913106
Sample std : 1.004459261894226
Minimum value: -3.832531690597534
Maximum value: 4.220885276794434
