<a href="https://colab.research.google.com/github/Tankasala25/PyTorch/blob/main/PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
print(torch.__version__)

2.8.0+cu126


In [3]:
scalar=torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.item()

7

In [5]:
scalar.ndim

0

In [6]:
scalar.shape

torch.Size([])

In [7]:
vector=torch.tensor([2,2])

In [8]:
vector

tensor([2, 2])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [11]:
matrix = torch.tensor([[1,2,3],
                       [4,5,6]])

In [12]:
matrix

tensor([[1, 2, 3],
        [4, 5, 6]])

In [13]:
matrix.ndim

2

In [14]:
matrix.shape

torch.Size([2, 3])

In [15]:
Tensor=torch.tensor([[[1,2,3],
                      [4,5,6],
                      [7,8,9]]])

In [16]:
Tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [17]:
Tensor.ndim

3

In [18]:
Tensor.shape

torch.Size([1, 3, 3])

In [19]:
#let's create the tensor of shape [2,3,3] with torch.tensor

In [20]:
tens=torch.tensor([[[1,2,3],
                    [4,5,6],
                    [7,8,9]],
                   [[10,11,12],
                    [13,14,15],
                    [16,17,18]]])

In [21]:
tens.shape

torch.Size([2, 3, 3])

In [22]:
#let's print out the shape of tensor [3,2,3]

In [23]:
tens1=torch.tensor([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])

In [24]:
tens1.shape

torch.Size([3, 2, 3])

In [25]:
tens1.ndim

3

In [26]:
#let's create a random tensors- rand function will take only shape not the elements or list

In [27]:
tensor1=torch.rand(1,3)

In [28]:
tensor1

tensor([[0.4008, 0.0366, 0.0642]])

In [29]:
torch.randn(2,3)

tensor([[ 0.2022,  0.2195, -0.0321],
        [ 1.4514, -1.3672,  0.2771]])

In [30]:
torch.randint(1,10,(2,3))

tensor([[7, 7, 9],
        [3, 7, 5]])

In [31]:
# creating and tensors with zeros and ones


In [32]:
torch.zeros(3,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [33]:
torch.ones(4,5)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

###creating a tensors with range function and like fucntion

In [34]:
tens2=torch.arange(0,10,2)

In [35]:
tens2

tensor([0, 2, 4, 6, 8])

In [36]:
tens3=torch.zeros_like(tens2)

In [37]:
tens4=torch.ones_like(tens2)

In [38]:
tens3

tensor([0, 0, 0, 0, 0])

In [39]:
tens4

tensor([1, 1, 1, 1, 1])

In [40]:
#tensor with different data types

In [41]:
tensor_32=torch.tensor([2.,3.],
                       dtype=None,
                       device=None,
                       requires_grad=False)

In [42]:
tensor_32

tensor([2., 3.])

###Converting one data type to another

In [43]:
tensor_16=tensor_32.type(torch.float16)

In [44]:
tensor_16

tensor([2., 3.], dtype=torch.float16)

In [45]:
# let's create a tesnsor and get some details about the tensor

In [46]:
rand1=torch.rand(2,3,dtype=torch.float16)

In [47]:
rand1

tensor([[0.9653, 0.1533, 0.5190],
        [0.0234, 0.2358, 0.3120]], dtype=torch.float16)

In [48]:
rand1.shape

torch.Size([2, 3])

In [49]:
rand1.dtype

torch.float16

In [50]:
rand1.device

device(type='cpu')

###Manipulating tensors

  we will perform addition, subtraction, multiplications , division and matrix multiplications

In [51]:
tensor4=torch.tensor([1,2,3])

In [52]:
tensor4

tensor([1, 2, 3])

In [53]:
tensor4 + 10

tensor([11, 12, 13])

In [54]:
tensor4=tensor4*10

In [55]:
tensor4

tensor([10, 20, 30])

In [56]:
tensor4-4

tensor([ 6, 16, 26])

In [57]:
tensor4/6

tensor([1.6667, 3.3333, 5.0000])

In [58]:
tensor4.add(10)

tensor([20, 30, 40])

In [59]:
tensor4.mul(2)

tensor([20, 40, 60])

In [60]:
tensor4.sub(5)

tensor([ 5, 15, 25])

In [61]:
tensor4.div(5)

tensor([2., 4., 6.])

### Matrix Mutliplication

In [62]:
#this is element-wise multiplication
tensor4 * tensor4

tensor([100, 400, 900])

In [63]:
torch.matmul(tensor4,tensor4)

tensor(1400)

In [64]:
%%time
value=0
for i in range(len(tensor4)):
  value+=tensor4[i]*tensor4[i]
print(value)

tensor(1400)
CPU times: user 1.34 ms, sys: 892 µs, total: 2.23 ms
Wall time: 2.34 ms


In [65]:
%%time
torch.matmul(tensor4,tensor4)

CPU times: user 501 µs, sys: 0 ns, total: 501 µs
Wall time: 508 µs


tensor(1400)

###Two things to remember while doing matrix multiplications
1.Inner dimensions must match - otherwise we will get error

(3,2)(3,2) - we will get error

(3,2)(2,3) -it will works

2.the resulting matrix will shape of outer dimensions

  (3,2)(2,3) - (3,3)

In [66]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[0.6306, 0.5680, 0.4664],
        [1.1694, 0.9725, 0.7051],
        [0.7626, 0.7376, 0.6642]])

In [67]:
torch.matmul(torch.rand(3,2),torch.rand(2,4))

tensor([[0.4969, 0.7457, 0.6991, 0.6699],
        [0.0958, 0.1531, 0.1639, 0.1201],
        [0.2837, 0.3782, 0.2514, 0.4287]])

In [68]:
torch.matmul(torch.rand(3,2),torch.rand(3,3))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x3)

In [69]:
tensor_a=torch.tensor([[1,2],[2,3]])

In [70]:
tensor_b=torch.tensor([[3,4],[4,5],[6,7]])

In [71]:
torch.matmul(tensor_a,tensor_b)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x2 and 3x2)

###Transpose

this function will change the axis or dimensions of tensor.

tensor.T

In [72]:
tensor_b.T

tensor([[3, 4, 6],
        [4, 5, 7]])

In [73]:
torch.matmul(tensor_a,tensor_b.T)

tensor([[11, 14, 20],
        [18, 23, 33]])

### Batch multiplication

Only the last two dims are used for matrix multiplication (m×n × n×p → m×p).

All earlier dims are batch dims.

Batch dims must either match or one of them must be 1 (for broadcasting).

In [74]:
A = torch.randn(1, 3, 4)  # (batch=1)
B = torch.randn(3, 4, 5)  # (batch=2)
C = torch.matmul(A, B)
print(C.shape)

torch.Size([3, 3, 5])


In [75]:
A = torch.randn(2, 3, 4)  # (batch=1)
B = torch.randn(3, 4, 5)  # (batch=2)
C = torch.matmul(A, B)
print(C.shape)

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 0

###Aggregate Functions

Let's look at agg func like min,max,mean,sum

In [76]:
tensor_ag=torch.arange(0,100,10)

In [77]:
tensor_ag

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [78]:
torch.min(tensor_ag),tensor_ag.min()

(tensor(0), tensor(0))

In [79]:
torch.max(tensor_ag),tensor_ag.max()

(tensor(90), tensor(90))

In [80]:
torch.mean(tensor_ag.type(torch.float32)),tensor_ag.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [81]:
torch.sum(tensor_ag),tensor_ag.sum()

(tensor(450), tensor(450))

### finding the positional min and max

In [82]:
tensor_ag.argmin(),torch.argmin(tensor_ag)

(tensor(0), tensor(0))

In [83]:
tensor_ag.argmax(),torch.argmax(tensor_ag)

(tensor(9), tensor(9))

###Reshaping

Reshaping changes the view of the same data into a new shape.

In [84]:
x=torch.arange(1.,10.)

In [85]:
x,x.shape,x.ndim


(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]), 1)

In [86]:
x.reshape(3,3)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [87]:
x.reshape(1,9)

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [88]:
x.reshape(9,1)

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

#View
Similar to reshape(), but it will share the same memory location of original one, so if we do any changes to view that will applied to original one.

In [89]:
z=x.view(1,9)
z

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [90]:
#we change the item at zeroth index
z[:,0]=10

In [91]:
z,x

(tensor([[10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]]),
 tensor([10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]))

#stacking

Stacking means joining multiple tensors together along a new axis.

Think of it like putting pages on top of each other to form a book.

Each page = one tensor

The book = stacked tensor (with an extra dimension).

In [92]:
x_stacked=torch.stack([x,x,x,x],dim=0)

In [93]:
x_stacked

tensor([[10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]])

In [94]:
x_stacked1=torch.stack([x,x,x,x],dim=0)

In [95]:
x_stacked1

tensor([[10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]])

In [96]:
a = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])
b = torch.tensor([[7, 8, 9],
                  [10,11,12]])

In [97]:
torch.stack((a, b), dim=0)


tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])

In [98]:
torch.stack((a, b), dim=1)

tensor([[[ 1,  2,  3],
         [ 7,  8,  9]],

        [[ 4,  5,  6],
         [10, 11, 12]]])

In [99]:
torch.stack((a, b), dim=2)

tensor([[[ 1,  7],
         [ 2,  8],
         [ 3,  9]],

        [[ 4, 10],
         [ 5, 11],
         [ 6, 12]]])

In [100]:
torch.vstack((a, b))

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

In [ ]:
torch.hstack((a, b))

#squeezing

torch.squeeze() removes dimensions of size 1 (also called “singleton dimensions”) from a tensor’s shape.

In [101]:
x=torch.zeros(1,3,1,5)

In [102]:
x.shape

torch.Size([1, 3, 1, 5])

In [103]:
x_squeezed=x.squeeze()

In [104]:
x_squeezed.shape

torch.Size([3, 5])

In [105]:
dim_squeezed=torch.squeeze(x,dim=2) #

In [106]:
dim_squeezed.shape

torch.Size([1, 3, 5])

In [107]:
dim1=x.squeeze(dim=0)

In [108]:
dim1.shape

torch.Size([3, 1, 5])

In [109]:
x = torch.tensor([5.])
print(x.shape)   # torch.Size([1])
print(torch.squeeze(x).shape)  # torch.Size([])


torch.Size([1])
torch.Size([])


###unsqueeze
Adds a new dimension of size 1.

In [110]:
x = torch.tensor([1, 2, 3])
x_unsq = x.unsqueeze(0)  # shape: (1, 3)
x_sq = torch.squeeze(x_unsq)  # shape: (3,)

In [111]:
x_unsq.ndim

2

In [112]:
x_sq.ndim

1

###Permute

You can rearrange any number of dimensions — more general than transpose.

In [113]:
x=torch.rand(224,224,3)

In [114]:
x.shape

torch.Size([224, 224, 3])

In [115]:
y=x.permute(2,0,1)

In [116]:
y.shape

torch.Size([3, 224, 224])

# Tensor Operation Differences (Short Notes)

### Differences Between `reshape`, `transpose`, and `permute`

| Function | Purpose | What It Does | Example Change | Notes |
|-----------|----------|---------------|----------------|-------|
| **`reshape()`** | Change shape | Rearranges elements into a new shape (no axis change) | `(2, 3, 4)` → `(3, 8)` | Same data order, just reshaped |
| **`transpose(dim0, dim1)`** | Swap two axes | Exchanges two dimensions only | `(2, 3, 4)` → `(3, 2, 4)` | Works for 2D/3D tensors |
| **`permute(dims)`** | Reorder all axes | Changes the order of *all* dimensions | `(2, 3, 4)` → `(4, 2, 3)` | Generalized version of transpose |

---

💡 **In short:**
- `reshape` → changes **shape**  
- `transpose` → swaps **two axes**  
- `permute` → **reorders all axes**

### Indexing

Indexing means accessing specific elements or slices from a tensor —
just like you do with lists or NumPy arrays.

In PyTorch, indexing works similarly to Python and NumPy.

In [118]:
x = torch.tensor([[[10, 20, 30],
                  [40, 50, 60],
                  [70, 80, 90]]])

In [119]:
x[0]

tensor([[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]])

In [120]:
x[0:,0]

tensor([[10, 20, 30]])

In [121]:
x[0:,0:,2]


tensor([[30, 60, 90]])

In [122]:
x[0:,1]

tensor([[40, 50, 60]])

In [123]:
x[0:,1:,1]

tensor([[50, 80]])

In [124]:
x[0,2,1:]

tensor([80, 90])

In [125]:
x[0,0:,1]

tensor([20, 50, 80])

### Numpy to Pytorch
torch.from_numpy(numpy_array)

###Pytorch to Numpy
tensor.numpy()

In [126]:
import torch
import numpy as np

np_array=np.arange(1.0,9.0)
tensor=torch.from_numpy(np_array)


In [127]:
np_array+=1
np_array,tensor

(array([2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [128]:
tensor=torch.ones(7)
numpy_tensor=tensor.numpy()

tensor=tensor+1
tensor,numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

###Reproducibility

Reproducibility means getting the same results every time you run your code —
even if your model uses random initialization, random shuffling, or random noise.

In PyTorch, you control this mainly by setting a random seed.

In [137]:
# Same seed → same results
torch.manual_seed(42)
r1 = torch.rand(2, 3)

torch.manual_seed(42)
r2 = torch.rand(2, 3)



# Different seed → different results
torch.manual_seed(7)
r3 = torch.rand(2, 3)

# Any integer works (1729 is just an example)
torch.manual_seed(1729)
r4 = torch.rand(2, 3)

r5=torch.rand(2,3)

torch.manual_seed(1729)

r6= torch.rand(2, 3)

r7=torch.rand(2,3)

print("Seed 42 - first:\n", r1)
print("\nSeed 42 - second (identical):\n", r2)
print(r1==r2)
print("\nSeed 7:\n", r3)
print("\nSeed 1729:\n", r4)
print("\nSeed 1729:\n", r5)
print("\nSeed 1729:\n", r6)
print("\nSeed 1729:\n", r7)
print(r4==r6)
print(r5==r7)


Seed 42 - first:
 tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

Seed 42 - second (identical):
 tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])
tensor([[True, True, True],
        [True, True, True]])

Seed 7:
 tensor([[0.5349, 0.1988, 0.6592],
        [0.6569, 0.2328, 0.4251]])

Seed 1729:
 tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])

Seed 1729:
 tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])

Seed 1729:
 tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])

Seed 1729:
 tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])
tensor([[True, True, True],
        [True, True, True]])
tensor([[True, True, True],
        [True, True, True]])
