<a href="https://colab.research.google.com/github/Tankasala25/PyTorch/blob/main/Pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###00. PyTorch Fundamentals Exercises
###1. Documentation reading
A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):

The documentation on [torch.Tensor](https://docs.pytorch.org/docs/stable/tensors.html#torch-tensor).

The documentation on [torch.cuda](https://docs.pytorch.org/docs/main/notes/cuda.html#cuda-semantics).

###2. Create a random tensor with shape (7, 7).

In [1]:
import torch

In [3]:
a=torch.rand(7,7)
a

tensor([[0.8247, 0.3328, 0.7563, 0.5062, 0.1898, 0.6381, 0.5151],
        [0.4490, 0.5660, 0.8441, 0.3261, 0.2411, 0.4545, 0.1729],
        [0.6181, 0.4473, 0.9254, 0.8532, 0.4913, 0.7564, 0.1666],
        [0.2218, 0.3921, 0.4026, 0.4881, 0.2460, 0.4712, 0.0730],
        [0.7947, 0.1538, 0.8281, 0.3947, 0.3229, 0.6942, 0.9052],
        [0.2530, 0.6131, 0.7715, 0.2793, 0.4771, 0.7284, 0.6777],
        [0.9020, 0.0832, 0.8731, 0.2942, 0.2100, 0.0403, 0.6609]])

###3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [4]:
b=torch.rand(1,7)
b.T

tensor([[0.3486],
        [0.4517],
        [0.8155],
        [0.4234],
        [0.7032],
        [0.4914],
        [0.2927]])

In [5]:
torch.matmul(a,b.T)

tensor([[1.8667],
        [1.6822],
        [2.2993],
        [1.2153],
        [2.0221],
        [2.0044],
        [1.5495]])

###Set the random seed to 0 and do 2 & 3 over again.

In [6]:
torch.manual_seed(0)
a=torch.rand(7,7)
b=torch.rand(1,7)
b.T
torch.matmul(a,b.T)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

###5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one)
If there is, set the GPU random seed to 1234.

In [7]:
torch.cuda.manual_seed(1234)

###6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

In [16]:
device="cuda" if torch.cuda.is_available() else "cpu"
torch.cuda.manual_seed(1234)
x=torch.rand(2,3,device=device)
x=x.to(device)
y=torch.rand(2,3,device=device)
print(device)
print(x)
print(x.device)
print(y)
print(y.device)

cuda
tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0')
cuda:0
tensor([[0.6208, 0.0276, 0.3255],
        [0.1114, 0.6812, 0.3608]], device='cuda:0')
cuda:0


###7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [17]:
x.shape

torch.Size([2, 3])

In [18]:
y.shape

torch.Size([2, 3])

In [23]:
y.T.shape

torch.Size([3, 2])

In [25]:
torch.matmul(x,y.T),torch.matmul(x,y.T).shape

(tensor([[0.2786, 0.7668],
         [0.7343, 0.6102]], device='cuda:0'),
 torch.Size([2, 2]))

#8. Find the maximum and minimum values of the output of 7.

In [26]:
torch.matmul(x,y.T).min()

tensor(0.2786, device='cuda:0')

In [27]:
torch.matmul(x,y.T).max()

tensor(0.7668, device='cuda:0')

###Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [28]:
torch.cuda.manual_seed(7)
x=torch.rand(1,1,1,10)
print(x)
print(x.shape)
y=x.squeeze()
print(y)
print(y.shape)

tensor([[[[0.0290, 0.4019, 0.2598, 0.3666, 0.0583, 0.7006, 0.0518, 0.4681,
           0.6738, 0.3315]]]])
torch.Size([1, 1, 1, 10])
tensor([0.0290, 0.4019, 0.2598, 0.3666, 0.0583, 0.7006, 0.0518, 0.4681, 0.6738,
        0.3315])
torch.Size([10])
