<a href="https://colab.research.google.com/github/Tankasala25/PyTorch/blob/main/tensor2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🧠 Tensor Basics — Shapes, *_like, Copies, Lists


## 📌 Tensor Shape
A tensor’s `.shape` shows its dimensions.  
For example: `(2, 2, 3)` means a 3D tensor with **2 blocks**, each block has **2 rows × 3 columns**.


In [ ]:
import torch

x = torch.empty(2, 2, 3)
print("x.shape:", x.shape)
print("x:\n", x)


x.shape: torch.Size([2, 2, 3])
x:
 tensor([[[2.3590e-36, 4.4268e-41, 2.3590e-36],
         [4.4268e-41, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 4.5898e-35, 2.3822e-44],
         [0.0000e+00, 1.5893e-39, 0.0000e+00]]])


## 📌 Creating same-shape tensors with `*_like`
If you want a new tensor with the **same shape** as an existing one:

- `empty_like` → uninitialized (garbage values).
- `zeros_like` → all zeros.
- `ones_like` → all ones.
- `rand_like` → random numbers between 0 and 1.


In [ ]:
empty_like_x = torch.empty_like(x)
zeros_like_x = torch.zeros_like(x)
ones_like_x  = torch.ones_like(x)
rand_like_x  = torch.rand_like(x)

print("empty_like_x:\n", empty_like_x, "\n")
print("zeros_like_x:\n", zeros_like_x, "\n")
print("ones_like_x:\n", ones_like_x, "\n")
print("rand_like_x:\n", rand_like_x)


empty_like_x:
 tensor([[[ 0.0000e+00,  0.0000e+00,  1.1967e-27],
         [ 0.0000e+00,  3.6248e-26,  0.0000e+00]],

        [[-7.1731e+25,  4.4267e-41,  1.4013e-45],
         [ 0.0000e+00,  1.6816e-44,  0.0000e+00]]]) 

zeros_like_x:
 tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]) 

ones_like_x:
 tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]]) 

rand_like_x:
 tensor([[[0.8338, 0.1065, 0.9135],
         [0.9611, 0.0627, 0.7334]],

        [[0.5868, 0.7894, 0.0218],
         [0.5524, 0.3272, 0.3907]]])


## 📌 Why `empty()` shows strange values
- `torch.empty()` does not clear memory — it just allocates space.  
- You see whatever random bytes were there.  
- If you want controlled values, use `.zero_()` or other initializers.


In [ ]:
a = torch.empty(3, 4)
print("Uninitialized a:\n", a)

a.zero_()
print("\nAfter zero_():\n", a)


Uninitialized a:
 tensor([[3.1352e-25, 0.0000e+00, 0.0000e+00, 1.4013e-45],
        [0.0000e+00, 0.0000e+00, 9.1084e-44, 0.0000e+00],
        [5.7938e-27, 0.0000e+00, 2.3589e-36, 4.4268e-41]])

After zero_():
 tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


## 📌 Creating tensors from Python data
If you already have lists/tuples, you can pass them directly into `torch.tensor()`.


In [ ]:
some_constants = torch.tensor([[3.1415926, 2.71828],
                               [1.61803,   0.0072897]])
print("some_constants:\n", some_constants)

some_integers = torch.tensor((2, 3, 5, 7, 11, 13, 17, 19))
print("\nsome_integers:\n", some_integers)

more_integers = torch.tensor(((2, 4, 6), [3, 6, 9]))
print("\nmore_integers:\n", more_integers)


some_constants:
 tensor([[3.1416, 2.7183],
        [1.6180, 0.0073]])

some_integers:
 tensor([ 2,  3,  5,  7, 11, 13, 17, 19])

more_integers:
 tensor([[2, 4, 6],
        [3, 6, 9]])


## 📌 Passing list variables to `torch.tensor`
Yes, you can pass variables containing lists directly.


In [ ]:
list1 = [1, 2, 3]
list2 = [4, 5, 6]

t1 = torch.tensor(list1)
t2 = torch.tensor(list2)

print("t1:", t1)
print("t2:", t2)

t_stacked = torch.tensor([list1, list2])   # 2D tensor
print("\nt_stacked:\n", t_stacked)


t1: tensor([1, 2, 3])
t2: tensor([4, 5, 6])

t_stacked:
 tensor([[1, 2, 3],
        [4, 5, 6]])


## 📌 Making independent copies of tensors
If you want the **same shape and same values** as another tensor (independent, not linked):

- `clone()` → makes an exact copy (same dtype, same device).
- `torch.tensor(x)` → also copies values but defaults to CPU unless specified.


In [ ]:
x = torch.tensor([[1., 2.],
                  [3., 4.]])

y_clone = x.clone()        # independent copy
y_tensor = torch.tensor(x) # independent copy (defaults to CPU)

x[0, 0] = 99.0

print("x:\n", x)
print("\ny_clone (unchanged):\n", y_clone)
print("\ny_tensor (unchanged):\n", y_tensor)


x:
 tensor([[99.,  2.],
        [ 3.,  4.]])

y_clone (unchanged):
 tensor([[1., 2.],
        [3., 4.]])

y_tensor (unchanged):
 tensor([[1., 2.],
        [3., 4.]])


/tmp/ipython-input-3479791493.py:5: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_tensor = torch.tensor(x) # independent copy (defaults to CPU)


# ❓ Doubts Recap

**Q1. `_like` gives same shape but different values?**  
✅ Yes, it copies the shape, not the values.  

**Q2. What if I want same values too?**  
✅ Use `clone()` or `torch.tensor(x)` → both give independent copies.  

**Q3. Can I pass Python list variables into `torch.tensor`?**  
✅ Yes. Works for single list (1D) or nested lists (2D, 3D...).  

