<a href="https://colab.research.google.com/github/Tankasala25/PyTorch/blob/main/Tensor3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 📓 PyTorch Tensors — Data Types, Math & Broadcasting

This notebook introduces PyTorch tensor **data types**, **math operations**, **broadcasting**, and some **linear algebra functions** in simple steps.


## 🔹 1. Tensor Data Types

When creating tensors, you can choose the **data type** (`dtype`).

- Integers (`int16`, `int32`, `int64`) → store whole numbers (no decimals).  
- Floats (`float32`, `float64`) → store decimals (used in ML).  
- Default type = `float32`.  

You can set `dtype` when creating a tensor, or later convert with `.to(dtype)`.


In [ ]:
import torch

# Integer tensor
a = torch.ones((2, 3), dtype=torch.int16)
print("a:\n", a, "\nwith dtype:", a.dtype)

# Float tensor
b = torch.rand((2, 3), dtype=torch.float64) * 20
print("\nb:\n", b, "\nwith dtype:", b.dtype)

# Convert floats to integers (truncate)
c = b.to(torch.int32)
print("\nc:\n", c, "\nwith dtype:", c.dtype)


a:
 tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16) 
with dtype: torch.int16

b:
 tensor([[ 6.3046, 15.9735, 15.0393],
        [18.1036, 15.2432,  3.8573]], dtype=torch.float64) 
with dtype: torch.float64

c:
 tensor([[ 6, 15, 15],
        [18, 15,  3]], dtype=torch.int32) 
with dtype: torch.int32


👉 **Key Idea:**  
- Integers drop fractions.  
- Floats keep decimals.  
- `.to(dtype)` changes type.  


## 🔹 2. Math with Tensors

You can do arithmetic directly on tensors. Operations apply **element by element**.


In [ ]:
ones = torch.zeros(2, 2) + 1
twos = torch.ones(2, 2) * 2
threes = (torch.ones(2, 2) * 7 - 1) / 2
fours = twos ** 2
sqrt2s = twos ** 0.5

print("ones:\n", ones)
print("twos:\n", twos)
print("threes:\n", threes)
print("fours:\n", fours)
print("sqrt2s:\n", sqrt2s)


ones:
 tensor([[1., 1.],
        [1., 1.]])
twos:
 tensor([[2., 2.],
        [2., 2.]])
threes:
 tensor([[3., 3.],
        [3., 3.]])
fours:
 tensor([[4., 4.],
        [4., 4.]])
sqrt2s:
 tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])


👉 **Key Idea:**  
Tensors = numbers in bulk. You can add, subtract, multiply, divide, square, or take roots.


## 🔹 3. Tensor Broadcasting

Broadcasting allows operations between different-shaped tensors.  

Rules:  
1. Compare shapes **right to left**.  
2. They are compatible if:  
   - Equal size, OR  
   - One size = `1`, OR  
   - Dimension missing.  
3. Else → error.  


In [ ]:
rand = torch.rand(2, 4)              # shape (2,4)
other = torch.ones(1, 4) * 2         # shape (1,4)
doubled = rand * other               # broadcast

print("rand:\n", rand)
print("\nother:\n", other)
print("\ndoubled:\n", doubled)
print("\nshapes:", rand.shape, other.shape, doubled.shape)


rand:
 tensor([[0.2103, 0.4097, 0.8421, 0.7839],
        [0.7225, 0.9838, 0.1466, 0.4488]])

other:
 tensor([[2., 2., 2., 2.]])

doubled:
 tensor([[0.4206, 0.8194, 1.6842, 1.5678],
        [1.4451, 1.9676, 0.2932, 0.8975]])

shapes: torch.Size([2, 4]) torch.Size([1, 4]) torch.Size([2, 4])


# 📓 PyTorch Broadcasting — Row and Column Expansion

This notebook explains **which row/column gets expanded** when broadcasting
occurs in PyTorch.


## Case 1 — One Row vs Two Rows

- `rand`: shape **(2,4)** → two rows, four columns  
- `other`: shape **(1,4)** → one row, four columns  

👉 Broadcasting rule: the single row is repeated for each row of `rand`.


In [ ]:
import torch

rand = torch.tensor([[1., 2., 3., 4.],
                     [5., 6., 7., 8.]])   # (2,4)

other = torch.tensor([[10., 20., 30., 40.]])  # (1,4)

print("rand:\n", rand)
print("\nother (1 row):\n", other)

expanded = other.expand_as(rand)   # broadcasted view
print("\nexpanded other:\n", expanded)

result = rand * other
print("\nresult (rand * other):\n", result)


rand:
 tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])

other (1 row):
 tensor([[10., 20., 30., 40.]])

expanded other:
 tensor([[10., 20., 30., 40.],
        [10., 20., 30., 40.]])

result (rand * other):
 tensor([[ 10.,  40.,  90., 160.],
        [ 50., 120., 210., 320.]])


## Case 2 — One Column vs Two Columns

- `rand`: shape **(2,4)** → two rows, four columns  
- `other`: shape **(2,1)** → two rows, one column  

👉 Broadcasting rule: the single column in each row is repeated across columns.


In [ ]:
rand = torch.tensor([[1., 2., 3., 4.],
                     [5., 6., 7., 8.]])   # (2,4)

other = torch.tensor([[10.],
                      [20.]])             # (2,1)

print("rand:\n", rand)
print("\nother (1 column per row):\n", other)

expanded = other.expand_as(rand)
print("\nexpanded other:\n", expanded)

result = rand * other
print("\nresult (rand * other):\n", result)


rand:
 tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])

other (1 column per row):
 tensor([[10.],
        [20.]])

expanded other:
 tensor([[10., 10., 10., 10.],
        [20., 20., 20., 20.]])

result (rand * other):
 tensor([[ 10.,  20.,  30.,  40.],
        [100., 120., 140., 160.]])


## Case 3 — Single Value (1×1) vs (2×4)

- `rand`: shape **(2,4)** → two rows, four columns  
- `other`: shape **(1,1)** → single value  

👉 Broadcasting rule: that single value is repeated across **all rows and columns**.


In [ ]:
rand = torch.tensor([[1., 2., 3., 4.],
                     [5., 6., 7., 8.]])   # (2,4)

other = torch.tensor([[10.]])              # (1,1)

print("rand:\n", rand)
print("\nother (1 value):\n", other)

expanded = other.expand_as(rand)
print("\nexpanded other:\n", expanded)

result = rand * other
print("\nresult (rand * other):\n", result)


rand:
 tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])

other (1 value):
 tensor([[10.]])

expanded other:
 tensor([[10., 10., 10., 10.],
        [10., 10., 10., 10.]])

result (rand * other):
 tensor([[10., 20., 30., 40.],
        [50., 60., 70., 80.]])


# ✅ Summary

- If **row dimension = 1** → that row is copied for all rows.  
- If **column dimension = 1** → that column is copied for all columns.  
- If both are `1` → the single value is copied everywhere.  

Broadcasting makes tensor math concise without explicit tiling or copying.



## 🔹 4. More Math Functions

PyTorch has hundreds of math functions. Here are a few categories:

- `abs` → absolute value  
- `ceil` / `floor` → round up / down  
- `clamp` → restrict values to a range  
- `sin`, `asin` → trig functions  
- `bitwise_xor` → binary operations  
- `eq` → elementwise comparison  
- Reductions → `max`, `mean`, `std`, `prod`, `unique`  


In [ ]:
import math

# Common
a = torch.rand(2, 4) * 2 - 1
print("a:\n", a)
print("\nabs(a):\n", torch.abs(a))
print("\nceil(a):\n", torch.ceil(a))
print("\nfloor(a):\n", torch.floor(a))
print("\nclamp(a, -0.5, 0.5):\n", torch.clamp(a, -0.5, 0.5))

# Trigonometric
angles = torch.tensor([0., math.pi/4, math.pi/2])
print("\nangles:\n", angles)
print("sin:\n", torch.sin(angles))
print("asin(sin):\n", torch.asin(torch.sin(angles)))

# Bitwise
b = torch.tensor([1, 5, 11])
c = torch.tensor([2, 7, 10])
print("\nbitwise_xor:\n", torch.bitwise_xor(b, c))

# Comparisons
d = torch.tensor([[1., 2.], [3., 4.]])
e = torch.ones(1, 2)
print("\neq(d, e):\n", torch.eq(d, e))

# Reductions
print("\nmax:", torch.max(d))
print("mean:", torch.mean(d))
print("std:", torch.std(d))
print("prod:", torch.prod(d))
print("unique:", torch.unique(torch.tensor([1,2,1,2])))


a:
 tensor([[ 0.7742, -0.9926,  0.0832, -0.8274],
        [ 0.0936,  0.4313, -0.5653, -0.0968]])

abs(a):
 tensor([[0.7742, 0.9926, 0.0832, 0.8274],
        [0.0936, 0.4313, 0.5653, 0.0968]])

ceil(a):
 tensor([[1., -0., 1., -0.],
        [1., 1., -0., -0.]])

floor(a):
 tensor([[ 0., -1.,  0., -1.],
        [ 0.,  0., -1., -1.]])

clamp(a, -0.5, 0.5):
 tensor([[ 0.5000, -0.5000,  0.0832, -0.5000],
        [ 0.0936,  0.4313, -0.5000, -0.0968]])

angles:
 tensor([0.0000, 0.7854, 1.5708])
sin:
 tensor([0.0000, 0.7071, 1.0000])
asin(sin):
 tensor([0.0000, 0.7854, 1.5708])

bitwise_xor:
 tensor([3, 2, 1])

eq(d, e):
 tensor([[ True, False],
        [False, False]])

max: tensor(4.)
mean: tensor(2.5000)
std: tensor(1.2910)
prod: tensor(24.)
unique: tensor([1, 2])


👉 **Key Idea:**  
- `abs`: absolute value (positive).  
- `ceil` / `floor`: round up / down.  
- `clamp`: force values into a range.  
- `sin`, `asin`: forward + inverse trig.  
- `bitwise_xor`: binary digit XOR.  
- `eq`: compare values → True/False.  
- `max`, `mean`, `std`, `prod`, `unique`: summarize values.  


## 🔹 5. Vectors & Linear Algebra

Linear algebra is the **engine of ML**.  
- Vectors = 1D arrays (directions)  
- Matrices = 2D arrays (transformations)  
- Operations like **cross product**, **matrix multiply**, and **SVD** are essential.  


In [ ]:
# Cross product
v1 = torch.tensor([1., 0., 0.])   # x-axis
v2 = torch.tensor([0., 1., 0.])   # y-axis
print("cross(v2,v1):", torch.linalg.cross(v2, v1))

# Matrix multiplication
m1 = torch.rand(2, 2)
m2 = torch.tensor([[3., 0.], [0., 3.]])
m3 = torch.linalg.matmul(m1, m2)

print("\nm1:\n", m1)
print("m3 = m1 @ (3I):\n", m3)

# Singular Value Decomposition
U, S, Vh = torch.linalg.svd(m3)
print("\nSVD(m3):")
print("U:\n", U)
print("S:\n", S)
print("Vh:\n", Vh)


cross(v2,v1): tensor([ 0.,  0., -1.])

m1:
 tensor([[0.7864, 0.5132],
        [0.8572, 0.8767]])
m3 = m1 @ (3I):
 tensor([[2.3591, 1.5395],
        [2.5715, 2.6300]])

SVD(m3):
U:
 tensor([[-0.6056, -0.7958],
        [-0.7958,  0.6056]])
S:
 tensor([4.6073, 0.4874])
Vh:
 tensor([[-0.7542, -0.6566],
        [-0.6566,  0.7542]])


👉 **Key Idea:**  
- Cross product → perpendicular vector.  
- Matmul → matrix multiplication, core of neural nets.  
- SVD → factorization into rotations + scales (used in PCA, compression).  


# 🎯 Wrap-Up

- **Data Types** → int vs float.  
- **Math Ops** → elementwise.  
- **Broadcasting** → smaller tensor expands.  
- **Functions** → abs, clamp, trig, bitwise, compare.  
- **Reductions** → max, mean, std, prod, unique.  
- **Linear Algebra** → cross product, matrix multiplication, SVD.  
